services:
  # ─────────────────────────────────────────────
  # Node.js API (Development — hot reload)
  # ─────────────────────────────────────────────
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./:/app 
      - /app/node_modules 
    env_file: .env
    environment:
      - NODE_ENV=development
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

  # ─────────────────────────────────────────────
  # Redis
  # ─────────────────────────────────────────────
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379" 
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
